# Generated by Django 3.2.8 on 2025-12-03 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Títol de l'esdeveniment", max_length=200, verbose_name='Títol')),
                ('description', models.TextField(help_text="Descripció detallada de l'esdeveniment", verbose_name='Descripció')),
                ('category', models.CharField(choices=[('gaming', 'Gaming'), ('music', 'Música'), ('talk', 'Xerrades'), ('education', 'Educació'), ('sports', 'Esports'), ('entertainment', 'Entreteniment'), ('technology', 'Tecnologia'), ('art', 'Art i Creativitat'), ('other', 'Altres')], max_length=50, verbose_name='Categoria')),
                ('scheduled_date', models.DateTimeField(help_text="Data i hora de l'esdeveniment", verbose_name='Data Programada')),
                ('status', models.CharField(choices=[('scheduled', 'Programat'), ('live', 'En Directe'), ('finished', 'Finalitzat'), ('cancelled', 'Cancel·lat')], default='scheduled', max_length=20, verbose_name='Estat')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/', verbose_name='Imatge de Portada')),
                ('max_viewers', models.PositiveIntegerField(default=100, help_text="Nombre màxim d'espectadors permesos", verbose_name='Màxim Espectadors')),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar com a esdeveniment destacat', verbose_name='Destacat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Creació')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualització')),
                ('tags', models.CharField(blank=True, help_text='Etiquetes separades per comes', max_length=500, verbose_name='Etiquetes')),
                ('stream_url', models.URLField(blank=True, help_text='URL del streaming o vídeo de demostració', max_length=500, verbose_name='URL del Streaming')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Esdeveniment',
                'verbose_name_plural': 'Esdeveniments',
                'ordering': ['-created_at'],
            },
        ),
    ]
